Add Google Analytics 4 support
wintercms/wn-googleanalytics-plugin pull request #4
Opened 2022-11-03 05:16 UTC by bennothommo

This PR introduces Google Analytics 4 support, in order to allow for this plugin to work when Google deprecates GA3/UA. I imagine that this will be released as a new major version of the plugin, since there won't be much use continuing to support GA3.

### New features introduced:

- Traffic Overview widget now allows a user to select the metric for the overview, between individual users, user sessions and page views (hits). They will also be able to select multiple metrics in order to view more metrics at once.

2022-11-03 07:46 UTC, bennothommo commented
<img width="2023" alt="Screen Shot 2022-11-03 at 3 44 42 pm" src="https://user-images.githubusercontent.com/15900351/199669503-9c10e8c9-c19d-489a-b608-ec2226707ab3.png">

2022-11-04 03:33 UTC, bennothommo commented
Demonstration of placeholder content while reports are deferred and loading in the background via AJAX:

<img width="2022" alt="Screen Shot 2022-11-04 at 11 32 31 am" src="https://user-images.githubusercontent.com/15900351/199879486-d1bef2bc-b7ad-4b76-b080-fd5cdfacdfe6.png">

2022-11-25 07:17 UTC, LukeTowers commented on reportwidgets/toppages/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/table-placeholder.svg') ?>"
Any asset files should be linked with Url::asset() instead of Url::to()

2022-11-29 20:04 UTC, LukeTowers requested changes

2022-11-29 20:04 UTC, LukeTowers commented on reportwidgets/browsers/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/bar-graph-placeholder.svg') ?>"
```suggestion
        src="<?= Url::asset('plugins/winter/googleanalytics/assets/images/bar-graph-placeholder.svg') ?>"
```

2022-11-29 20:04 UTC, LukeTowers commented on reportwidgets/toppages/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/table-placeholder.svg') ?>"
```suggestion
        src="<?= Url::asset('plugins/winter/googleanalytics/assets/images/table-placeholder.svg') ?>"
```

2022-11-29 20:04 UTC, LukeTowers commented on reportwidgets/trafficgoal/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/goal-placeholder.svg') ?>"
```suggestion
        src="<?= Url::asset('plugins/winter/googleanalytics/assets/images/goal-placeholder.svg') ?>"
```

2022-11-29 20:04 UTC, LukeTowers commented on reportwidgets/trafficoverview/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/line-graph-placeholder.svg') ?>"
```suggestion
        src="<?= Url::asset('plugins/winter/googleanalytics/assets/images/line-graph-placeholder.svg') ?>"
```

2022-11-29 20:04 UTC, LukeTowers commented on reportwidgets/trafficsources/partials/_widget.php
> +        src="<?= Url::to('plugins/winter/googleanalytics/assets/images/pie-graph-placeholder.svg') ?>"
```suggestion
        src="<?= Url::asset('plugins/winter/googleanalytics/assets/images/pie-graph-placeholder.svg') ?>"
```

2022-11-30 03:35 UTC, merged